language: node_js

services:
  - docker

before_install:
  - npm install
  - npm install -g npm

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jinjietan/react-webpack:latest .
  - docker push jinjietan/react-webpack:latest
