language: node_js
node_js:
  - "12"
services:
  - docker



script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jinjietan/react-webpack:latest .
  - docker push jinjietan/react-webpack:latest
